# Generated by Django 4.1.1 on 2022-10-20 04:41

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lodging_id', models.IntegerField(help_text='lodging의 index')),
                ('like_date', models.DateField(auto_now_add=True, help_text='숙소 좋아요 누른 시점')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='accounts.account')),
            ],
        ),
    ]
